@startuml Kundenverwaltung Zustandsdiagramm

title Zustandsdiagramm - Kundenverwaltung\nSoll-Zustand

state "Kunde (Kundenverwaltung)" as KundeState {
    [*] --> NeuAngelegt : Registrierung / Erfassung

    state "Neu angelegt" as NeuAngelegt #LightYellow {
        NeuAngelegt : Stammdaten erfasst
        NeuAngelegt : Noch keine Bestellungen
        NeuAngelegt : E-Mail nicht verifiziert
    }

    state "Aktiv" as KundeAktiv #LightGreen {
        KundeAktiv : Kann Boote mieten
        KundeAktiv : Kann Liegeplaetze reservieren
        KundeAktiv : Vollstaendige Stammdaten

        state "Ohne Vertrag" as OhneVertrag #LightGreen {
            OhneVertrag : Keine aktiven Vertraege
            OhneVertrag : Kann buchen
        }

        state "Mit Vertrag" as MitVertrag #LightBlue {
            MitVertrag : Aktive Mietvertraege
            MitVertrag : Laufende Reservierungen
        }

        state "Zahlungsverzug" as Zahlungsverzug #Orange {
            Zahlungsverzug : Offene Zahlungen
            Zahlungsverzug : Mahnung versendet
        }
    }

    state "Inaktiv" as KundeInaktiv #LightGray {
        KundeInaktiv : Deaktiviert
        KundeInaktiv : Keine Buchungen moeglich
        KundeInaktiv : Daten archiviert
    }

    state "Gesperrt" as KundeGesperrt #Salmon {
        KundeGesperrt : Zahlungsausfall
        KundeGesperrt : Vertragsbruch
        KundeGesperrt : Keine Buchungen moeglich
    }

    ' Transitionen
    NeuAngelegt --> KundeAktiv : E-Mail bestaetigt /\nDaten vollstaendig
    NeuAngelegt --> KundeInaktiv : Timeout /\nKeine Bestaetigung

    OhneVertrag --> MitVertrag : Reservierung\nbestaetigt
    MitVertrag --> OhneVertrag : Vertrag beendet /\nKuendigung
    MitVertrag --> Zahlungsverzug : Zahlung ueberfaellig

    Zahlungsverzug --> MitVertrag : Zahlung eingegangen
    Zahlungsverzug --> KundeGesperrt : Zahlungsausfall\n[nach Mahnung]

    KundeAktiv --> KundeInaktiv : Kunde kuendigt /\nDeaktivierung
    KundeAktiv --> KundeGesperrt : Vertragsbruch /\nBetrug

    KundeGesperrt --> KundeAktiv : Sperrung aufgehoben\n[Zahlung/Klaerung]
    KundeGesperrt --> KundeInaktiv : Endgueltige\nDeaktivierung

    KundeInaktiv --> KundeAktiv : Reaktivierung\n[auf Anfrage]
    KundeInaktiv --> [*] : Daten geloescht\n[DSGVO]
}

@enduml
